(source melpa)

(depends-on "alchemist")
(depends-on "color-theme-solarized")
(depends-on "dockerfile-mode")
(depends-on "editorconfig")
(depends-on "edts")
(depends-on "elixir-mode")
(depends-on "erlang")
(depends-on "evil")
(depends-on "js3-mode")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "tern")
(depends-on "tern-auto-complete")
