(source "gnu" "http://elpa.emacs-china.org/gnu/")
(source "melpa" "http://elpa.emacs-china.org/melpa/")

(depends-on "alchemist")
(depends-on "color-theme-solarized")
(depends-on "company")
(depends-on "company-tern")
(depends-on "counsel")
(depends-on "dockerfile-mode")
(depends-on "editorconfig")
(depends-on "edts")
(depends-on "ein")
(depends-on "elixir-mode")
(depends-on "elpy")
(depends-on "erlang")
(depends-on "evil")
(depends-on "flycheck")
(depends-on "groovy-mode")
(depends-on "helm")
(depends-on "helm-core")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "nginx-mode")
(depends-on "nodejs-repl")
(depends-on "org-pomodoro")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "py-autopep8")
(depends-on "reveal-in-osx-finder")
(depends-on "smartparens")
(depends-on "swiper")
(depends-on "tern")
(depends-on "vue-mode")
(depends-on "yaml-mode")
